# -*- coding: utf-8 -*-
"""Copy of gemni_fixed_dintial_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iIOVrlNt1bjCKFl8pwRR09M10DTpzA-Z
"""

import gymnasium as gym
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon, Rectangle
import matplotlib.animation as animation

# --- Constants ---
DT = 0.5
GRID_LIMIT = 200.0
MARGIN = 40.0

class SpacecraftEnv(gym.Env):
    def __init__(self):
        super().__init__()
        self.half_s = 15.0
        self.dock_y_local = 8.25
        self.position_log = []

        # Local Geometry (30x30 Body)
        self.body_poly = np.array([[-15, -15], [15, -15], [15, 15], [-15, 15]])

        # CHASER: Original Trapezoid Probe
        self.ch_probe_local = np.array([
            [15, self.dock_y_local + 2.5],
            [15, self.dock_y_local - 2.5],
            [19, self.dock_y_local - 1.5],
            [19, self.dock_y_local + 1.5]
        ])

        # TARGET: Improved Assembly with SMALLER Funnel
        self.tgt_base_local = np.array([
            [-15, self.dock_y_local + 2.0], [-17, self.dock_y_local + 2.0],
            [-17, self.dock_y_local - 2.0], [-15, self.dock_y_local - 2.0]
        ])

        # Reduced cone size (Width 12 instead of 16)
        self.tgt_funnel_local = np.array([
            [-17, self.dock_y_local + 2.0], # Inner top
            [-25, self.dock_y_local + 6.0], # Outer top (Smaller)
            [-25, self.dock_y_local - 6.0], # Outer bottom (Smaller)
            [-17, self.dock_y_local - 2.0]  # Inner bottom
        ])

    def _get_R(self, theta):
        return np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])

    def _transform(self, points, state):
        return (points @ self._get_R(state[2]).T) + state[:2]

    def reset(self, start_pos, start_theta):
        self.target_state = np.array([165.0, 100.0, 0.0], dtype=np.float32)
        self.chaser_state = np.array([start_pos[0], start_pos[1], start_theta], dtype=np.float32)
        self.initial_cond = (start_pos[0], start_pos[1], start_theta)
        self.position_log = []
        return np.zeros(9), {}

    def step(self, action):
        self.chaser_state += action * DT

        # --- GRID ENFORCEMENT ---
        self.chaser_state[0] = np.clip(self.chaser_state[0], 0, GRID_LIMIT)
        self.chaser_state[1] = np.clip(self.chaser_state[1], 0, GRID_LIMIT)

        R_tgt = self._get_R(self.target_state[2])
        entry_pt = (np.array([-25.0, self.dock_y_local]) @ R_tgt.T) + self.target_state[:2]
        dist = np.linalg.norm(self.chaser_state[:2] - entry_pt)

        if dist > 60: stage = 1
        elif dist > 35: stage = 2
        elif dist > 15: stage = 3
        else: stage = 4

        self.position_log.append({
            'chaser': self.chaser_state.copy(),
            'target': self.target_state.copy(),
            'stage': stage
        })
        return np.zeros(9), 0, False, False, {}

def save_mp4(position_log, env, filename):
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_xlim(-10, GRID_LIMIT + MARGIN); ax.set_ylim(-10, GRID_LIMIT + MARGIN)
    ax.set_aspect('equal')
    ax.grid(True, linestyle=':', alpha=0.3)

    # Boundary
    boundary = Rectangle((0,0), GRID_LIMIT, GRID_LIMIT, lw=2, ec='red', fc='none', ls='--')
    ax.add_patch(boundary)

    # HUD
    x0, y0, t0 = env.initial_cond
    hud_label = f"INIT: ({x0}, {y0}) | θ: {np.degrees(t0):.1f}°"
    ax.text(GRID_LIMIT, -15, hud_label, fontsize=10, fontweight='bold', ha='right',
            bbox=dict(facecolor='white', alpha=0.8))

    colors = {1: 'blue', 2: 'cyan', 3: 'green', 4: 'gold'}
    lines = {s: ax.plot([], [], color=colors[s], lw=2.5, label=f'Stage {s}')[0] for s in colors}

    t_body = Polygon(np.zeros((4, 2)), color='#4D4D4D')
    t_base = Polygon(np.zeros((4, 2)), color='#4D4D4D')
    t_cone = Polygon(np.zeros((4, 2)), fill=False, edgecolor='black', lw=2)
    c_body = Polygon(np.zeros((4, 2)), color='#D6001C')
    c_probe = Polygon(np.zeros((4, 2)), color='silver', ec='black')

    def init():
        for p in [t_body, t_base, t_cone, c_body, c_probe]: ax.add_patch(p)
        return list(lines.values()) + [t_body, t_base, t_cone, c_body, c_probe]

    def update(frame):
        s = position_log[frame]
        t_body.set_xy(env._transform(env.body_poly, s['target']))
        t_base.set_xy(env._transform(env.tgt_base_local, s['target']))
        t_cone.set_xy(env._transform(env.tgt_funnel_local, s['target']))
        c_body.set_xy(env._transform(env.body_poly, s['chaser']))
        c_probe.set_xy(env._transform(env.ch_probe_local, s['chaser']))

        for stage, line in lines.items():
            pts = np.array([p['chaser'][:2] for p in position_log[:frame+1] if p['stage'] == stage])
            if pts.size: line.set_data(pts[:, 0], pts[:, 1])
        return list(lines.values()) + [t_body, t_base, t_cone, c_body, c_probe]

    ani = animation.FuncAnimation(fig, update, frames=len(position_log), init_func=init, blit=True, interval=20)
    plt.legend(loc='upper left')
    ani.save(filename, writer='ffmpeg', fps=50)
    plt.close(fig)

def get_smart_path(P0, P2, num_pts=100):
    if abs(P0[1] - P2[1]) < 8:
        return [P0 + (P2 - P0) * (i / (num_pts - 1)) for i in range(num_pts)]
    P1 = np.array([P0[0], P2[1]])
    t = np.linspace(0, 1, num_pts)
    return [(1-s)**2 * P0 + 2*(1-s)*s * P1 + s**2 * P2 for s in t]

def run_scenario(env, start_pos, start_theta, filename):
    env.reset(start_pos, start_theta)
    R_t = env._get_R(env.target_state[2])

    entry_pt = (np.array([-25.0, env.dock_y_local]) @ R_t.T) + env.target_state[:2]
    dock_pt = (np.array([-17.0, env.dock_y_local]) @ R_t.T) + env.target_state[:2]

    waypoints = get_smart_path(np.array(start_pos), entry_pt)
    waypoints.append(dock_pt)

    idx = 0
    max_steps = 1500
    for step in range(max_steps):
        target_wp = waypoints[min(idx, len(waypoints)-1)]
        R_c = env._get_R(env.chaser_state[2])
        probe_tip = (np.array([19, env.dock_y_local]) @ R_c.T) + env.chaser_state[:2]

        dist = np.linalg.norm(probe_tip - target_wp)
        if dist < 2.5 and idx < len(waypoints) - 1:
            idx += 1
            continue

        if (idx >= len(waypoints) - 1 and dist < 0.2) or step == max_steps - 1:
            break

        err_pos = target_wp - probe_tip
        err_ang = env.target_state[2] - env.chaser_state[2]
        action = np.array([err_pos[0]*0.18, err_pos[1]*0.18, err_ang*0.25])
        env.step(action)

    print(f"Finalizing {filename}")
    save_mp4(env.position_log, env, filename)

if __name__ == "__main__":
    env = SpacecraftEnv()
    test_cases = [
        ([20, 20], -0.6, "case_1_low.mp4"),
        ([20, 180], 0.6, "case_2_high.mp4"),
        ([130, 190], 1.5, "case_3_top.mp4"),
        ([10, 108], 0.0, "case_4_straight.mp4")
    ]
    for p, t, f in test_cases:
        run_scenario(env, p, t, f)