# -*- coding: utf-8 -*-
"""gemni_fixed_dintial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwVWbQM2Nbzk3KuCQTcHP7dj0qKWxkz4
"""

import gymnasium as gym
from gymnasium import spaces
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon
import matplotlib.animation as animation

# --- Constants ---
DT = 0.5
MAX_DISTANCE = 250

class SpacecraftEnv(gym.Env):
    def __init__(self):
        super().__init__()
        self.half_s = 15.0
        self.dock_y_local = 8.25 # 6.75 from top edge
        self.position_log = []

        # Local Geometry (30x30 Body)
        self.body_poly = np.array([[-15, -15], [15, -15], [15, 15], [-15, 15]])

        # CHASER: Probe on the RIGHT face (+x)
        self.ch_probe_local = np.array([
            [15, self.dock_y_local + 2.5], [15, self.dock_y_local - 2.5],
            [19, self.dock_y_local - 1.5], [19, self.dock_y_local + 1.5]
        ])

        # TARGET: Cone on the LEFT face (-x)
        self.tgt_base_local = np.array([
            [-15, self.dock_y_local + 2.5], [-15, self.dock_y_local - 2.5],
            [-22.62, self.dock_y_local - 2.5], [-22.62, self.dock_y_local + 2.5]
        ])
        self.tgt_funnel_local = np.array([
            [-27.7, self.dock_y_local + 5.0], [-22.62, self.dock_y_local + 2.5],
            [-22.62, self.dock_y_local - 2.5], [-27.7, self.dock_y_local - 5.0]
        ])

    def _get_R(self, theta):
        return np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])

    def _transform(self, points, state):
        return (points @ self._get_R(state[2]).T) + state[:2]

    def reset(self, start_pos, start_theta):
        self.target_state = np.array([185.0, 118.0, 0.0], dtype=np.float32)
        self.chaser_state = np.array([start_pos[0], start_pos[1], start_theta], dtype=np.float32)
        self.position_log = []
        return np.zeros(9), {}

    def step(self, action):
        self.chaser_state += action * DT
        R_tgt = self._get_R(self.target_state[2])
        entry_pt = (np.array([-27.7, self.dock_y_local]) @ R_tgt.T) + self.target_state[:2]
        dist = np.linalg.norm(self.chaser_state[:2] - entry_pt)

        # Stage thresholds
        if dist > 62: stage = 1
        elif dist > 40: stage = 2
        elif dist > 25: stage = 3
        else: stage = 4

        self.position_log.append({
            'chaser': self.chaser_state.copy(),
            'target': self.target_state.copy(),
            'stage': stage
        })
        return np.zeros(9), 0, False, False, {}

def save_mp4(position_log, env, filename):
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_xlim(0, MAX_DISTANCE); ax.set_ylim(0, MAX_DISTANCE); ax.set_aspect('equal')
    ax.grid(True, linestyle=':', alpha=0.3)

    colors = {1: 'blue', 2: 'cyan', 3: 'green', 4: 'gold'}
    lines = {s: ax.plot([], [], color=colors[s], lw=2.5, label=f'Stage {s}')[0] for s in colors}

    # Restored Patches
    t_body = Polygon(np.zeros((4, 2)), color='#4D4D4D')
    t_base = Polygon(np.zeros((4, 2)), color='#4D4D4D')
    t_v = Polygon(np.zeros((4, 2)), fill=False, edgecolor='black', lw=1.5)
    c_body = Polygon(np.zeros((4, 2)), color='#D6001C')
    c_probe = Polygon(np.zeros((4, 2)), color='white', ec='black')

    def init():
        for p in [t_body, t_base, t_v, c_body, c_probe]: ax.add_patch(p)
        return list(lines.values()) + [t_body, t_base, t_v, c_body, c_probe]

    def update(frame):
        s = position_log[frame]
        t_body.set_xy(env._transform(env.body_poly, s['target']))
        t_base.set_xy(env._transform(env.tgt_base_local, s['target']))
        t_v.set_xy(env._transform(env.tgt_funnel_local, s['target']))
        c_body.set_xy(env._transform(env.body_poly, s['chaser']))
        c_probe.set_xy(env._transform(env.ch_probe_local, s['chaser']))

        for stage, line in lines.items():
            pts = np.array([p['chaser'][:2] for p in position_log[:frame+1] if p['stage'] == stage])
            if pts.size: line.set_data(pts[:, 0], pts[:, 1])
        return list(lines.values()) + [t_body, t_base, t_v, c_body, c_probe]

    ani = animation.FuncAnimation(fig, update, frames=len(position_log), init_func=init, blit=True, interval=25)
    plt.legend(loc='upper left')
    ani.save(filename, writer='ffmpeg', fps=40)
    plt.close()

def run_scenario(env, start_pos, start_theta, filename):
    env.reset(start_pos, start_theta)
    R_t = env._get_R(env.target_state[2])
    final_goal = (np.array([-15, env.dock_y_local]) @ R_t.T) + env.target_state[:2]

    # Generate Arc Waypoints
    mid_x = (start_pos[0] + final_goal[0]) / 2
    mid_y = max(start_pos[1], final_goal[1]) + 50
    waypoints = [np.array([mid_x, mid_y]), final_goal + np.array([-40, 5]), final_goal]

    current_wp_idx = 0
    for _ in range(1200):
        target_wp = waypoints[current_wp_idx]
        R_c = env._get_R(env.chaser_state[2])
        probe_tip = (np.array([19, env.dock_y_local]) @ R_c.T) + env.chaser_state[:2]

        dist_to_wp = np.linalg.norm(probe_tip - target_wp)
        if dist_to_wp < 1.5 and current_wp_idx < len(waypoints) - 1:
            current_wp_idx += 1
            continue

        if current_wp_idx == len(waypoints) - 1 and dist_to_wp < 0.25:
            env.chaser_state[:2] += (target_wp - probe_tip)
            env.chaser_state[2] = env.target_state[2]
            env.step(np.array([0,0,0]))
            break

        err_pos = target_wp - probe_tip
        err_angle = env.target_state[2] - env.chaser_state[2]
        gain = 0.04 if current_wp_idx < 1 else 0.02
        action = np.array([err_pos[0]*gain, err_pos[1]*gain, err_angle*0.06])
        env.step(action)

    save_mp4(env.position_log, env, filename)

if __name__ == "__main__":
    env = SpacecraftEnv()
    # Scenario A: Low start (Original-like)
    run_scenario(env, [30, 20], -0.94, "arc_low_start.mp4")
    # Scenario B: High start
    run_scenario(env, [25, 200], 0.5, "arc_high_start.mp4")