# -*- coding: utf-8 -*-
"""Another copy of gemni_fixed_dintial_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LlKcbkbx0vN9bwDpC3giWuLRuspOYW86
"""

import gymnasium as gym
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon, Rectangle
import matplotlib.animation as animation

# --- Constants ---
DT = 0.5
GRID_LIMIT = 200.0
MARGIN = 40.0
# Specific Obstacle Position from User
OBS_X = 100.5
OBS_Y = 61.0
OBSTACLE_POS = np.array([OBS_X, OBS_Y])
OBSTACLE_SIZE = 30.0

class SpacecraftEnv(gym.Env):
    def __init__(self):
        super().__init__()
        self.half_s = 15.0
        self.dock_y_local = 8.25
        self.position_log = []

        # Local Geometry
        self.body_poly = np.array([[-15, -15], [15, -15], [15, 15], [-15, 15]])
        # Chaser Probe (Original Dimensions)
        self.ch_probe_local = np.array([[15, 10.75], [15, 5.75], [19, 6.75], [19, 9.75]])

        # Target Geometry (Compact Cone)
        self.tgt_base_local = np.array([[-15, 10.25], [-17, 10.25], [-17, 6.25], [-15, 6.25]])
        self.tgt_funnel_local = np.array([[-17, 10.25], [-25, 14.25], [-25, 2.25], [-17, 6.25]])

    def _get_R(self, theta):
        return np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])

    def _transform(self, points, state):
        return (points @ self._get_R(state[2]).T) + state[:2]

    def reset(self, start_pos, start_theta):
        self.target_state = np.array([165.0, 100.0, 0.0], dtype=np.float32)
        self.chaser_state = np.array([start_pos[0], start_pos[1], start_theta], dtype=np.float32)
        self.initial_cond = (start_pos[0], start_pos[1], start_theta)
        self.position_log = []
        return np.zeros(9), {}

    def step(self, action):
        self.chaser_state += action * DT
        self.chaser_state[0] = np.clip(self.chaser_state[0], 0, GRID_LIMIT)
        self.chaser_state[1] = np.clip(self.chaser_state[1], 0, GRID_LIMIT)

        R_tgt = self._get_R(self.target_state[2])
        entry_pt = (np.array([-25.0, self.dock_y_local]) @ R_tgt.T) + self.target_state[:2]
        dist = np.linalg.norm(self.chaser_state[:2] - entry_pt)

        stage = 1 if dist > 60 else 2 if dist > 35 else 3 if dist > 15 else 4
        self.position_log.append({'chaser': self.chaser_state.copy(), 'target': self.target_state.copy(), 'stage': stage})
        return np.zeros(9), 0, False, False, {}

def save_mp4(position_log, env, filename):
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_xlim(-10, GRID_LIMIT + MARGIN); ax.set_ylim(-10, GRID_LIMIT + MARGIN)
    ax.set_aspect('equal')
    ax.grid(True, linestyle=':', alpha=0.3)

    # Boundary & Obstacle
    ax.add_patch(Rectangle((0,0), GRID_LIMIT, GRID_LIMIT, lw=2, ec='red', fc='none', ls='--'))
    # Obstacle Square (30x30)
    obs_patch = Rectangle(OBSTACLE_POS - OBSTACLE_SIZE/2, OBSTACLE_SIZE, OBSTACLE_SIZE,
                          color='#333333', hatch='xx', label='Obstacle')
    ax.add_patch(obs_patch)

    # HUD
    x0, y0, t0 = env.initial_cond
    ax.text(GRID_LIMIT, -15, f"INIT: ({x0}, {y0}) | θ: {np.degrees(t0):.1f}°", ha='right', bbox=dict(facecolor='white', alpha=0.8))

    colors = {1: 'blue', 2: 'cyan', 3: 'green', 4: 'gold'}
    lines = {s: ax.plot([], [], color=colors[s], lw=2.5, label=f'Stage {s}')[0] for s in colors}

    patches = [Polygon(np.zeros((4, 2)), color='#4D4D4D'), Polygon(np.zeros((4, 2)), color='#4D4D4D'),
               Polygon(np.zeros((4, 2)), fill=False, ec='black', lw=2), Polygon(np.zeros((4, 2)), color='#D6001C'),
               Polygon(np.zeros((4, 2)), color='silver', ec='black')]

    def init():
        for p in patches: ax.add_patch(p)
        return list(lines.values()) + patches

    def update(frame):
        s = position_log[frame]
        patches[0].set_xy(env._transform(env.body_poly, s['target']))
        patches[1].set_xy(env._transform(env.tgt_base_local, s['target']))
        patches[2].set_xy(env._transform(env.tgt_funnel_local, s['target']))
        patches[3].set_xy(env._transform(env.body_poly, s['chaser']))
        patches[4].set_xy(env._transform(env.ch_probe_local, s['chaser']))
        for stage, line in lines.items():
            pts = np.array([p['chaser'][:2] for p in position_log[:frame+1] if p['stage'] == stage])
            if pts.size: line.set_data(pts[:, 0], pts[:, 1])
        return list(lines.values()) + patches

    ani = animation.FuncAnimation(fig, update, frames=len(position_log), init_func=init, blit=True, interval=20)
    plt.legend(loc='upper left'); ani.save(filename, writer='ffmpeg', fps=50); plt.close(fig)

def run_scenario(env, start_pos, start_theta, filename):
    env.reset(start_pos, start_theta)
    R_t = env._get_R(env.target_state[2])
    entry_pt = (np.array([-25.0, env.dock_y_local]) @ R_t.T) + env.target_state[:2]
    dock_pt = (np.array([-17.0, env.dock_y_local]) @ R_t.T) + env.target_state[:2]

    waypoints = [np.array(start_pos), entry_pt, dock_pt]
    idx = 0
    for step in range(2000):
        target_wp = waypoints[min(idx, len(waypoints)-1)]
        R_c = env._get_R(env.chaser_state[2])
        probe_tip = (np.array([19, env.dock_y_local]) @ R_c.T) + env.chaser_state[:2]

        # --- Potential Field Obstacle Avoidance ---
        # We check the distance from the chaser's center to the obstacle center
        vec_to_obs = env.chaser_state[:2] - OBSTACLE_POS
        dist_to_obs = np.linalg.norm(vec_to_obs)

        repulsion = np.array([0.0, 0.0])
        # Activate repulsion if within 40cm of the obstacle center
        if dist_to_obs < 40:
            # Force is stronger as the chaser gets closer
            repulsion = (vec_to_obs / (dist_to_obs**3)) * 6000

        err_pos = target_wp - probe_tip
        err_ang = env.target_state[2] - env.chaser_state[2]

        # Combine guidance and repulsion
        action_pos = (err_pos * 0.15) + repulsion
        action = np.array([action_pos[0], action_pos[1], err_ang * 0.2])

        env.step(action)

        if np.linalg.norm(probe_tip - target_wp) < 2.5 and idx < len(waypoints)-1: idx += 1
        if (idx >= len(waypoints)-1 and np.linalg.norm(probe_tip - target_wp) < 0.2): break

    print(f"Saving scenario with obstacle at {OBSTACLE_POS}...")
    save_mp4(env.position_log, env, filename)

if __name__ == "__main__":
    env = SpacecraftEnv()
    scenarios = [
        ([20, 61], 0.0, "obs_avoid_direct.mp4"), # Directly blocked path
        ([20, 20], -0.6, "obs_avoid_low.mp4"),   # Must climb over obstacle
        ([20, 180], 0.6, "obs_avoid_high.mp4")   # Path mostly clear
    ]
    for p, t, f in scenarios: run_scenario(env, p, t, f)

import gymnasium as gym
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon, Rectangle
import matplotlib.animation as animation

# --- Constants ---
DT = 0.5
GRID_LIMIT = 200.0
MARGIN = 40.0

# Obstacle positioned a bit lower on the Y-axis
OBSTACLE_POS = np.array([83.5, 74.0])
OBSTACLE_SIZE = 30.0

class SpacecraftEnv(gym.Env):
    def __init__(self):
        super().__init__()
        self.dock_y_local = 8.25
        self.position_log = []
        # Chaser Body
        self.body_poly = np.array([[-15, -15], [15, -15], [15, 15], [-15, 15]])
        # Chaser Probe (Original Dimensions)
        self.ch_probe_local = np.array([[15, 10.75], [15, 5.75], [19, 6.75], [19, 9.75]])
        # Target Geometry
        self.tgt_base_local = np.array([[-15, 10.25], [-17, 10.25], [-17, 6.25], [-15, 6.25]])
        self.tgt_funnel_local = np.array([[-17, 10.25], [-25, 14.25], [-25, 2.25], [-17, 6.25]])

    def _get_R(self, theta):
        return np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])

    def _transform(self, points, state):
        return (points @ self._get_R(state[2]).T) + state[:2]

    def reset(self, start_pos, start_theta):
        # Target fixed at (170, 100)
        self.target_state = np.array([170.0, 100.0, 0.0], dtype=np.float32)
        self.chaser_state = np.array([start_pos[0], start_pos[1], start_theta], dtype=np.float32)
        self.initial_cond = (start_pos[0], start_pos[1], start_theta)
        self.position_log = []
        return np.zeros(9), {}

    def step(self, action):
        self.chaser_state += action * DT
        # Hard boundary constraint
        self.chaser_state[0] = np.clip(self.chaser_state[0], 0, GRID_LIMIT)
        self.chaser_state[1] = np.clip(self.chaser_state[1], 0, GRID_LIMIT)

        R_tgt = self._get_R(self.target_state[2])
        entry_pt = (np.array([-25.0, self.dock_y_local]) @ R_tgt.T) + self.target_state[:2]
        dist = np.linalg.norm(self.chaser_state[:2] - entry_pt)

        stage = 1 if dist > 60 else 2 if dist > 35 else 3 if dist > 15 else 4
        self.position_log.append({'chaser': self.chaser_state.copy(), 'target': self.target_state.copy(), 'stage': stage})
        return np.zeros(9), 0, False, False, {}

def save_mp4(position_log, env, filename):
    fig, ax = plt.subplots(figsize=(8, 8))
    ax.set_xlim(-10, GRID_LIMIT + MARGIN); ax.set_ylim(-10, GRID_LIMIT + MARGIN)
    ax.set_aspect('equal')
    ax.grid(True, linestyle=':', alpha=0.3)

    # Visual grid limit
    ax.add_patch(Rectangle((0,0), GRID_LIMIT, GRID_LIMIT, lw=2, ec='red', fc='none', ls='--'))
    # Obstacle
    ax.add_patch(Rectangle(OBSTACLE_POS - OBSTACLE_SIZE/2, OBSTACLE_SIZE, OBSTACLE_SIZE,
                          color='#333333', hatch='//', label='Obstacle'))

    # HUD: Positioned at bottom-right to avoid stage legend
    x0, y0, t0 = env.initial_cond
    hud_txt = f"INITIAL CONDITIONS\nX: {x0} | Y: {y0}\nAngle: {np.degrees(t0):.1f}°"
    ax.text(GRID_LIMIT + 30, 0, hud_txt, fontsize=9, fontweight='bold',
            bbox=dict(facecolor='white', alpha=0.8), ha='right', va='bottom')

    colors = {1: 'blue', 2: 'cyan', 3: 'green', 4: 'gold'}
    lines = {s: ax.plot([], [], color=colors[s], lw=2.5, label=f'Stage {s}')[0] for s in colors}
    patches = [Polygon(np.zeros((4, 2)), color='#4D4D4D'), Polygon(np.zeros((4, 2)), color='#4D4D4D'),
               Polygon(np.zeros((4, 2)), fill=False, ec='black', lw=2), Polygon(np.zeros((4, 2)), color='#D6001C'),
               Polygon(np.zeros((4, 2)), color='silver', ec='black')]

    def init():
        for p in patches: ax.add_patch(p)
        return list(lines.values()) + patches

    def update(frame):
        s = position_log[frame]
        patches[0].set_xy(env._transform(env.body_poly, s['target']))
        patches[1].set_xy(env._transform(env.tgt_base_local, s['target']))
        patches[2].set_xy(env._transform(env.tgt_funnel_local, s['target']))
        patches[3].set_xy(env._transform(env.body_poly, s['chaser']))
        patches[4].set_xy(env._transform(env.ch_probe_local, s['chaser']))
        for stage, line in lines.items():
            pts = np.array([p['chaser'][:2] for p in position_log[:frame+1] if p['stage'] == stage])
            if pts.size: line.set_data(pts[:, 0], pts[:, 1])
        return list(lines.values()) + patches

    ani = animation.FuncAnimation(fig, update, frames=len(position_log), init_func=init, blit=True, interval=20)
    plt.legend(loc='upper left'); ani.save(filename, writer='ffmpeg', fps=50); plt.close(fig)

def run_scenario(env, start_pos, start_theta, filename):
    env.reset(start_pos, start_theta)
    R_t = env._get_R(env.target_state[2])

    # Waypoint points
    entry_pt = (np.array([-25.0, env.dock_y_local]) @ R_t.T) + env.target_state[:2]
    dock_pt = (np.array([-17.0, env.dock_y_local]) @ R_t.T) + env.target_state[:2]

    # "UP" Waypoint: Clears the obstacle by moving to a higher Y-coord
    avoid_up_pt = np.array([OBSTACLE_POS[0], OBSTACLE_POS[1] + 45])

    waypoints = [avoid_up_pt, entry_pt, dock_pt]
    idx = 0

    for step in range(2500):
        target_wp = waypoints[min(idx, len(waypoints)-1)]
        R_c = env._get_R(env.chaser_state[2])
        probe_tip = (np.array([19, env.dock_y_local]) @ R_c.T) + env.chaser_state[:2]

        err_pos = target_wp - probe_tip
        err_ang = env.target_state[2] - env.chaser_state[2]

        # P-Control
        action = np.array([err_pos[0]*0.15, err_pos[1]*0.15, err_ang*0.2])
        env.step(action)

        # Threshold for waypoint switching
        if np.linalg.norm(probe_tip - target_wp) < 3.5 and idx < len(waypoints)-1:
            idx += 1
            continue
        # Finish simulation
        if (idx >= len(waypoints)-1 and np.linalg.norm(probe_tip - target_wp) < 0.2):
            break

    save_mp4(env.position_log, env, filename)

if __name__ == "__main__":
    env = SpacecraftEnv()
    # Chaser starts LOW (20, 20), obstacle is at (100.5, 85).
    # Chaser will go UP to (100.5, 130) then DOWN to docking entry.
    run_scenario(env, [20, 20], -0.5, "up_and_over_avoidance.mp4")